import { CalisthenicsExercise } from "./types";

export const CALISTHENICS_PROGRESSION_TREE: CalisthenicsExercise[] = [
  // PUSH PROGRESSION
  {
    id: "push-1",
    name: "Incline Wall / Countertop Push-Up",
    category: "Push",
    level: "Beginner",
    progressionStep: 1,
    maxStep: 6,
    description: "Hands elevated on wall/counter. Builds foundational scapular control and chest endurance.",
    equipmentNeeded: "Floor / Wall",
  },
  {
    id: "push-2",
    name: "Knee / Incline Ground Push-Up",
    category: "Push",
    level: "Beginner",
    progressionStep: 2,
    maxStep: 6,
    description: "Knees on floor or hands on sturdy low chair. Keep core braced in a straight line.",
    equipmentNeeded: "Floor",
  },
  {
    id: "push-3",
    name: "Standard Floor Push-Up",
    category: "Push",
    level: "Intermediate",
    progressionStep: 3,
    maxStep: 6,
    description: "Full range of motion: chest touches floor, lock out elbows with protraction at top.",
    equipmentNeeded: "Floor",
  },
  {
    id: "push-4",
    name: "Diamond / Close-Grip Push-Up",
    category: "Push",
    level: "Intermediate",
    progressionStep: 4,
    maxStep: 6,
    description: "Hands form diamond shape under sternum. High triceps and anterior deltoid emphasis.",
    equipmentNeeded: "Floor",
  },
  {
    id: "push-5",
    name: "Archer / Pseudo Planche Push-Up",
    category: "Push",
    level: "Advanced",
    progressionStep: 5,
    maxStep: 6,
    description: "Shift bodyweight to one arm dynamically, or lean forward with hands at hip level.",
    equipmentNeeded: "Floor",
  },
  {
    id: "push-6",
    name: "One-Arm Push-Up / Full Planche Push-Up",
    category: "Push",
    level: "Elite",
    progressionStep: 6,
    maxStep: 6,
    description: "Unilateral mastery or straight-arm horizontal levitation push.",
    equipmentNeeded: "Floor",
  },

  // PULL PROGRESSION
  {
    id: "pull-1",
    name: "Doorframe / Bed-Sheet Inverted Row",
    category: "Pull",
    level: "Beginner",
    progressionStep: 1,
    maxStep: 6,
    description: "Anchor sheet in closed door or grasp doorframe. Pull chest to hands with active lats.",
    equipmentNeeded: "Door / Table",
  },
  {
    id: "pull-2",
    name: "Under-Table Horizontal Inverted Row",
    category: "Pull",
    level: "Beginner",
    progressionStep: 2,
    maxStep: 6,
    description: "Lie under sturdy dining table, grip edge with palms facing you. Pull chest to table underside.",
    equipmentNeeded: "Sturdy Table or Low Bar",
  },
  {
    id: "pull-3",
    name: "Dead Hangs & Scapular Pull-Ups",
    category: "Pull",
    level: "Intermediate",
    progressionStep: 3,
    maxStep: 6,
    description: "Hang with active shoulder depression. Retract scapulae without bending elbows.",
    equipmentNeeded: "Pull-up bar or High Ledge",
  },
  {
    id: "pull-4",
    name: "Negative (Eccentric) & Banded Pull-Ups",
    category: "Pull",
    level: "Intermediate",
    progressionStep: 4,
    maxStep: 6,
    description: "Jump to chin over bar, then lower yourself under 4-5 seconds strict control.",
    equipmentNeeded: "Pull-up bar",
  },
  {
    id: "pull-5",
    name: "Strict Dead-Stop Pull-Ups & Chest-to-Bar",
    category: "Pull",
    level: "Advanced",
    progressionStep: 5,
    maxStep: 6,
    description: "Full dead hang to explosive pull touching clavicle/chest to bar without swinging.",
    equipmentNeeded: "Pull-up bar",
  },
  {
    id: "pull-6",
    name: "Strict Bar Muscle-Up / Front Lever Row",
    category: "Pull",
    level: "Elite",
    progressionStep: 6,
    maxStep: 6,
    description: "Transition over the bar smoothly or row while suspended in horizontal front lever.",
    equipmentNeeded: "Pull-up bar",
  },

  // LEGS PROGRESSION
  {
    id: "leg-1",
    name: "Assisted Chair Squat & Glute Bridges",
    category: "Legs",
    level: "Beginner",
    progressionStep: 1,
    maxStep: 5,
    description: "Controlled descent to chair, press through heels. Hip thrusts on carpet for posterior chain.",
    equipmentNeeded: "Chair / Floor",
  },
  {
    id: "leg-2",
    name: "Full Bodyweight Deep Squat (ATG)",
    category: "Legs",
    level: "Beginner",
    progressionStep: 2,
    maxStep: 5,
    description: "Full range of motion below parallel, knees tracking toes, upright torso.",
    equipmentNeeded: "Floor",
  },
  {
    id: "leg-3",
    name: "Bulgarian Split Squat & Cossack Squat",
    category: "Legs",
    level: "Intermediate",
    progressionStep: 3,
    maxStep: 5,
    description: "Rear foot elevated on bed/couch. Deep unilateral quad and hip mobility overload.",
    equipmentNeeded: "Couch / Chair",
  },
  {
    id: "leg-4",
    name: "Box Pistol Squats & Nordic Curls (Feet Anchored)",
    category: "Legs",
    level: "Advanced",
    progressionStep: 4,
    maxStep: 5,
    description: "Single-leg squat lowering to box, plus eccentric hamstring lowering under sofa.",
    equipmentNeeded: "Sofa / Floor",
  },
  {
    id: "leg-5",
    name: "Full Free Pistol Squat & Shrimp Squat",
    category: "Legs",
    level: "Elite",
    progressionStep: 5,
    maxStep: 5,
    description: "Strict unilateral bodyweight squat down to heel and explode back up with zero support.",
    equipmentNeeded: "Floor",
  },

  // CORE & SKILL
  {
    id: "core-1",
    name: "Deadbug & Plank Hold",
    category: "Core",
    level: "Beginner",
    progressionStep: 1,
    maxStep: 5,
    description: "Anterior pelvic tilt elimination. Press lower back flat into floor.",
    equipmentNeeded: "Floor",
  },
  {
    id: "core-2",
    name: "Hollow Body Rock & Hanging Knee Raises",
    category: "Core",
    level: "Intermediate",
    progressionStep: 2,
    maxStep: 5,
    description: "Gymnastics hollow position. Ribs pinned down, legs pointed.",
    equipmentNeeded: "Floor / Bar",
  },
  {
    id: "core-3",
    name: "Tuck L-Sit (Floor or Chairs) & Toes-To-Bar",
    category: "Core",
    level: "Intermediate",
    progressionStep: 3,
    maxStep: 5,
    description: "Depress scapulae between 2 sturdy chairs or floor, raise knees to 90 degrees.",
    equipmentNeeded: "2 Chairs or Floor",
  },
  {
    id: "core-4",
    name: "Full Floor L-Sit Hold (15-30s)",
    category: "Core",
    level: "Advanced",
    progressionStep: 4,
    maxStep: 5,
    description: "Straight legs parallel to ground supported purely by straight-arm floor press.",
    equipmentNeeded: "Floor",
  },
  {
    id: "core-5",
    name: "V-Sit & Dragon Flag (Rocky)",
    category: "Core",
    level: "Elite",
    progressionStep: 5,
    maxStep: 5,
    description: "Full body levitation anchored only by shoulder blades on bench/floor.",
    equipmentNeeded: "Floor / Sturdy post",
  },
];
